import { VideoData, OptimizationResult, TargetViews, BrandingSettings } from '../src/types';

export function generateExportReport(
  video: VideoData,
  optimization: OptimizationResult,
  targetViews?: TargetViews,
  branding?: BrandingSettings
): {
  markdown: string;
  text: string;
  json: string;
} {
  const brand = branding?.brandName || "Tooni TV";
  const country = branding?.targetCountry || "United States";
  const viewsTarget = targetViews
    ? `\n- Target Views / Min: ${targetViews.perMinute || 'N/A'}\n- Target Views / Hour: ${targetViews.perHour || 'N/A'}\n- Target Views / Day: ${targetViews.perDay || 'N/A'}\n- Target Views / Month: ${targetViews.perMonth || 'N/A'}\n*(Disclaimer: User-defined optimization targets, not guaranteed views)*`
    : 'None set';

  const markdown = `# TOONI SEO AI — OPTIMIZATION REPORT
**Platform:** Tooni SEO AI | **Brand:** ${brand}
**Target Audience:** ${country} 🇺🇸 | **Date:** ${new Date().toLocaleDateString('en-US', { dateStyle: 'full' })}

---

## 1. ORIGINAL VIDEO AUDIT (FACT)
- **Title:** ${video.title}
- **Channel:** ${video.channel}
- **Video ID:** \`${video.id}\`
- **URL:** ${video.url}
- **Recorded Views:** ${video.views !== null ? video.views.toLocaleString() : 'Data unavailable (OAuth required)'}
- **Likes:** ${video.likes !== null ? video.likes.toLocaleString() : 'Data unavailable'}
- **Comments:** ${video.comments !== null ? video.comments.toLocaleString() : 'Data unavailable'}
- **Publish Date:** ${video.publishDate || 'N/A'}
- **Current Tags:** ${(video.tags || []).join(', ') || 'None provided'}

---

## 2. SEO OPTIMIZATION SCORES (ANALYSIS)
- **Baseline (Before) Score:** ${optimization.beforeScores.overall}/100
- **Optimized (After) Score:** ${optimization.afterScores.overall}/100 (+${optimization.afterScores.overall - optimization.beforeScores.overall} pts)
- **Title Score:** ${optimization.beforeScores.title}/100 ➔ **${optimization.afterScores.title}/100**
- **Description Score:** ${optimization.beforeScores.description}/100 ➔ **${optimization.afterScores.description}/100**
- **Keywords Score:** ${optimization.beforeScores.keywords}/100 ➔ **${optimization.afterScores.keywords}/100**
- **Tags Score:** ${optimization.beforeScores.tags}/100 ➔ **${optimization.afterScores.tags}/100**
- **Thumbnail Score:** ${optimization.beforeScores.thumbnail}/100 ➔ **${optimization.afterScores.thumbnail}/100**
- **Hook & Retention Score:** ${optimization.beforeScores.hook}/100 ➔ **${optimization.afterScores.hook}/100**
- **CTR Packaging Score:** ${optimization.beforeScores.ctr}/100 ➔ **${optimization.afterScores.ctr}/100**

---

## 3. USER OPTIMIZATION TARGETS (USER TARGET)
${viewsTarget}

---

## 4. AI OPTIMIZED TITLES (AI RECOMMENDATION)
### Primary Recommended Title:
> **${optimization.primaryTitle}**  
*(Length: ${optimization.primaryTitle.length} chars | Predicted CTR: 11.5%)*

### 5 Alternative Title Frameworks:
${optimization.optimizedTitles.map((t, idx) => `${idx + 1}. **[${t.type}]** ${t.title}  
   *(${t.charCount} chars | CTR: ${t.predictedCTR} | Score: ${t.score}/100)*`).join('\n')}

---

## 5. OPTIMIZED DESCRIPTION (AI RECOMMENDATION)
\`\`\`
${optimization.optimizedDescription}
\`\`\`

---

## 6. EXACTLY 20 USA KEYWORDS (AI RECOMMENDATION)
${optimization.optimizedKeywords.map((k, i) => `${i + 1}. ${k}`).join('\n')}

---

## 7. EXACTLY 20 TAGS (AI RECOMMENDATION)
\`\`\`
${optimization.optimizedTags.join(', ')}
\`\`\`

---

## 8. EXACTLY 5 HASHTAGS (AI RECOMMENDATION)
${optimization.suggestedHashtags.join(' ')}

---

## 9. HOOK & RETENTION BLUEPRINT (AI RECOMMENDATION)
- **Current Hook Diagnosis:** ${optimization.hookRewrites.hookProblem}
- **Opening 5 Seconds:** "${optimization.hookRewrites.first5Sec}"
- **Next 15 Seconds:** "${optimization.hookRewrites.first15Sec}"
- **Visual Action Cue:** ${optimization.hookRewrites.visualActionCue}

---

## 10. THUMBNAIL CLEAN REDESIGN PLAN (AI RECOMMENDATION)
- **Core Concept:** ${optimization.ctrPackaging.thumbnailConcept}
- **Badge Text (3 words max):** "${optimization.ctrPackaging.thumbnailOverlayText}"
- **Contrast & Color Advice:** ${optimization.ctrPackaging.colorContrastAdvice}
- **Curiosity Gap:** ${optimization.ctrPackaging.curiosityGap}
- **Mobile Rule:** ${optimization.ctrPackaging.mobileFrictionRule}

---
*Generated by Tooni SEO AI Platform for ${brand}. Optimized for USA Search & Recommendation Algorithms.*
`;

  const text = markdown.replace(/[*#`>]/g, '');

  const json = JSON.stringify(
    {
      platform: "Tooni SEO AI",
      brand,
      generatedAt: new Date().toISOString(),
      video,
      optimization,
      targetViews,
      branding
    },
    null,
    2
  );

  return { markdown, text, json };
}
